source 'https://rubygems.org'

gem 'rack'
gem 'rack-test'
gem 'sinatra'
gem 'foreman'
gem 'httparty'
gem 'awesome_print'
gem 'hashie'
gem 'activesupport'
gem 'octokit', '~> 4.0'
gem 'rspec'
gem 'simplecov'
