- "{{pr.html_url}}
   *Purpose*
   {{prt.purpose}}

   *Implementation*
   {{prt.implementation}}
   {{#prt.has_trello_card}}

   *Trello Card:*
   {{prt.trello_card_url}}
   {{/prt.has_trello_card}}
"
