- "{{base/prefix}} {{base/group}}'s {{pl.total}} most {{base/wanted}} changes for {{pl.repo}}"
- "{{base/group}}, {{base/group}}, and {{base/group}} unite in support of these {{pl.total}} {{adjective}} changes to {{pl.repo}}"
- "try not to cry when you see these {{pl.total}} {{adjective}} changes"
- "scientists uncover {{pr.deletions}} {{base/badj}} {{base/delword}} and {{pr.additions}} {{base/gadj}} {{base/addword}} that {{base/suffix}}"
- "{{pl.user}} made {{pl.total}} {{adjective}} changes to {{pl.repo}}, and you won't {{verb.present.first}} what happened!"
- "{{pl.user}} made {{pl.total}} changes to {{pl.repo}}, and the results are {{adjective}}!"
- "what happens when you make {{pl.total}} changes to {{pl.repo}}? {{pl.user}} found out, and you can too."
- "{{pl.user}} {{base/addword2}} {{pr.additions}} things, then {{base/delword2}} {{pr.deletions}} things. what happened next will shock you"
- "{{pl.total}} {{adjective}} ways to make {{pl.repo}} a better place"
